SaveEmployee/SaveEmployee/Models/StudentResult.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UniversityApplication.Models
{
    public class StudentResult
    {
        [Required]
        [DisplayName("Student Reg. No.")]
        public string StudentResultRegNo { get; set; }
        [DisplayName("Name")]
        [NotMapped]
        public string StudentResultName { get; set; }
        [DisplayName("Email")]
        [NotMapped]
        public string StudentResultEmail { get; set; }
        [DisplayName("Department")]
        [NotMapped]
        public string StudentResultDepartmentCode { get; set; }
        [Required]
        [DisplayName("Select Course")]
        public string StudentResultCourse { get; set; }
        [Required]
        [DisplayName("Select Grade Letter")]
        public string StudentResultGrade { get; set; }
        [Key]
        public int StudentResultId { get; set; }
    }
}

SaveEmployee/SaveEmployee/Controllers/StudentResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using UniversityApplication.BLL;
using UniversityApplication.Context;
using UniversityApplication.Models;

namespace UniversityApplication.Controllers
{
    public class StudentResultsController : Controller
    {
        private ApplicationContext db = new ApplicationContext();
        //ResultManager resultManager = new ResultManager();

        public ActionResult SaveResult()
        {
            GenerateDropDownValue();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveResult([Bind(Include = "StudentResultRegNo,StudentResultName,StudentResultEmail,StudentResultDepartmentCode,StudentResultCourse,StudentResultGrade")] StudentResult studentResult)
        {
            GenerateDropDownValue();
            ViewBag.Message = "Result Not saved";
            ViewBag.Status = "Error";

           if (ModelState.IsValid)
            {
                try
                {
                    db.StudentResults.Add(studentResult);
                    db.SaveChanges();
                    ModelState.Clear();
                    ViewBag.Status = "Success";
                    ViewBag.Message = "Success! Result Successfully Saved."; 
                }
                catch (Exception)
                {
                    ViewBag.Status = "Error";
                    ViewBag.Message = "Required! All data are required.";
                }

                return View();
            }
           ModelState.Clear();
            return View();
        }

        private void GenerateDropDownValue()
        {
            List<Student> allRegisteredStudents = new List<Student>();
            List<SelectListItem> students = new List<SelectListItem>();

            List<CourseStudent> allCourses = new List<CourseStudent>();

            using (ApplicationContext db = new ApplicationContext())
            {
                allRegisteredStudents = db.Students.OrderBy(a => a.StudentRegNo).ToList();
            }

            foreach (var student in allRegisteredStudents)
            {
                students.Add(

                    new SelectListItem()
                    {
                        Value = student.StudentRegNo,
                        Text = student.StudentRegNo
                    }
                    );
            }
            ViewBag.Students = students;

            ViewBag.CourseCode = new SelectList(allCourses, "CourseStudentCourse", "CourseStudentCourse");

            ViewBag.StudentName = "";
            ViewBag.StudentEmail = "";
            ViewBag.StudentDepartment = "";

            //var results = resultManager.GetResults();

            List<SelectListItem> resultList = new List<SelectListItem>()
            {
                new SelectListItem {Text = "A+", Value = "A+"},
                new SelectListItem {Text = "A", Value = "A"},
                new SelectListItem {Text = "A-", Value = "A-"},
                new SelectListItem {Text = "B+", Value = "B+"},
                new SelectListItem {Text = "B", Value = "B"},
                new SelectListItem {Text = "B-", Value = "B-"},
                new SelectListItem {Text = "C+", Value = "C+"},
                new SelectListItem {Text = "C", Value = "C"},
                new SelectListItem {Text = "C-", Value = "C-"},
                new SelectListItem {Text = "D+", Value = "D+"},
                new SelectListItem {Text = "D", Value = "D"},
                new SelectListItem {Text = "D-", Value = "D-"},
                new SelectListItem {Text = "F", Value = "F"},
            };

            //foreach (var result in results)
            //{
            //    resultList.Add(

            //        new SelectListItem()
            //        {
            //            Value = result,
            //            Text = result
            //        }
            //        );
            //}

            ViewBag.Result = resultList;
        }
        public JsonResult GetStudentName(string studentRegNo)
        {
            string name = "";

            if (!string.IsNullOrEmpty(studentRegNo))
            {
                using (ApplicationContext db = new ApplicationContext())
                {
                    name = db.Students.Where(c => c.StudentRegNo == studentRegNo).Select(p => p.StudentName).Single();
                }
            }
            if (Request.IsAjaxRequest())
            {
                return new JsonResult
                {
                    Data = name,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            else
            {
                return new JsonResult
                {
                    Data = "Not valid request",
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
        }

        public JsonResult GetStudentEmail(string studentRegNo)
        {
            string email = "";

            if (!string.IsNullOrEmpty(studentRegNo))
            {
                using (ApplicationContext db = new ApplicationContext())
                {
                    email = db.Students.Where(c => c.StudentRegNo == studentRegNo).Select(p => p.StudentEmail).Single();
                }
            }
            if (Request.IsAjaxRequest())
            {
                return new JsonResult
                {
                    Data = email,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            else
            {
                return new JsonResult
                {
                    Data = "Not valid request",
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
        }

        public JsonResult GetStudentDepartment(string studentRegNo)
        {
            string departmentCode = "";
            string department = "";

            if (!string.IsNullOrEmpty(studentRegNo))
            {
                using (ApplicationContext db = new ApplicationContext())
                {
                    departmentCode = db.Students.Where(c => c.StudentRegNo == studentRegNo).Select(p => p.StudentDepartmentCode).Single();
                    department = db.Departments.Where(c => c.DepartmentCode == departmentCode).Select(p => p.DepartmentName).Single();
                }
            }
            if (Request.IsAjaxRequest())
            {
                return new JsonResult
                {
                    Data = department,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            else
            {
                return new JsonResult
                {
                    Data = "Not valid request",
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
        }
        public JsonResult GetCourseCode(string departmentName)
        {
            List<CourseStudent> allCourses = new List<CourseStudent>();

            
            if (departmentName != null)
            {
                using (ApplicationContext db = new ApplicationContext())
                {
                    allCourses = db.CoursesStudents.Where(a => a.CourseStudentRegNo.Equals(departmentName)).OrderBy(p=>p.CourseStudentCourse).ToList();
                }
            }
            if (Request.IsAjaxRequest())
            {
                return new JsonResult
                {
                    Data = allCourses,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            else
            {
                return new JsonResult
                {
                    Data = "Not valid request",
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SaveEmployee/SaveEmployee/Views/StudentResults/Create.cshtml
@model UniversityApplication.Models.StudentResult

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StudentResult</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentResultRegNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentResultRegNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentResultRegNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentResultName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentResultName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentResultName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentResultEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentResultEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentResultEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentResultDepartmentCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentResultDepartmentCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentResultDepartmentCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentResultCourse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentResultCourse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentResultCourse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentResultGrade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentResultGrade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentResultGrade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SaveEmployee/SaveEmployee/Views/StudentResults/SaveResult.cshtml
@model UniversityApplication.Models.StudentResult

@{
    ViewBag.Title = "SaveResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="sidebar">
        <ul>
            <li><a href="../Departments/Create">Save Department</a></li>
            <li><a href="../Departments/ShowAllDepartments">View Departments</a></li>
            <li><a href="../Courses/Create">Save Course</a></li>
            <li><a href="../Teachers/Create">Save Teacher</a></li>
            <li><a href="../CourseTeacher/AssignCourse">Course Assign to Teacher</a></li>
            <li><a href="../CourseStaticss/CourseStatistics">View Course Statics</a></li>
            <li><a href="../Students/Create">Register Student</a></li>
            <li><a href="../Classrooms/AllocateClassRoom">Allocate Classrooms</a></li>
            <li><a href="../Classrooms/ClassScheduleAndRoomAllocation">Class Schedule and Room Allocation</a></li>
            <li><a href="../CourseStudents/StudentToCourse">Enroll in a Course</a></li>
            <li class="corners"><a href="../StudentResults/SaveResult">Save Student Result</a></li>
            <li><a href="../ViewResult/Create">View Result</a></li>
            <li><a href="../Unassign/UnassignCourse">Unassign All Courses</a></li>
            <li><a href="../Unassign/Unallocate">Unallocate All Classrooms</a></li>
        </ul>
    </div>

    <div style="background-color: white; padding-left: 25%; width: 80%; height: 100%;">
        <div class="container body-content">
            <br />
            <div class="form-horizontal">
                <h4>Save Student Result</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.StudentResultRegNo, htmlAttributes: new { @class = "col-md-2 labelStyle" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.StudentResultRegNo, new SelectList(ViewBag.Students, "Value", "Text"), "Select Student", new { @class = "form-control hideOnClick" })
                        @Html.ValidationMessageFor(model => model.StudentResultRegNo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StudentResultName, htmlAttributes: new { @class = "col-md-2 labelStyle" })
                    <div class="col-md-10">
                        @Html.LabelFor(model => model.StudentResultName, new { @id = "StudentResultName", @class = "col-md-2 labelStyle" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StudentResultEmail, htmlAttributes: new { @class = "col-md-2 labelStyle" })
                    <div class="col-md-10">
                        @Html.LabelFor(model => model.StudentResultEmail, new { @id = "StudentResultEmail", @class = "col-md-2 labelStyle" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StudentResultDepartmentCode, htmlAttributes: new { @class = "col-md-2 labelStyle" })
                    <div class="col-md-10">
                        @Html.LabelFor(model => model.StudentResultDepartmentCode, new { @id = "StudentResultDepartmentCode", @class = "col-md-2 labelStyle" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StudentResultCourse, htmlAttributes: new { @class = "col-md-2 labelStyle" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.StudentResultCourse, new SelectList(ViewBag.CourseCode, "Value", "Text"), "Select Course", new { @class = "form-control hideOnClick" })
                        @Html.ValidationMessageFor(model => model.StudentResultCourse, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StudentResultGrade, htmlAttributes: new { @class = "col-md-2 labelStyle" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.StudentResultGrade, new SelectList(ViewBag.Result, "Value", "Text"), "Select Grade", new { @class = "form-control hideOnClick" })
                        @Html.ValidationMessageFor(model => model.StudentResultGrade, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class=" col-sm-5">
                    </div>
                    <div class="col-sm-5">
                        <input type="submit" value="Save" class="btn btn-default" style="width:100px; height:30px" />
                    </div>
                </div>


                @if (ViewBag.Status == "Success")
                {
                    <div class="alert alert-success" id="hideThis">
                        <p>@ViewBag.Message</p>
                    </div>
                }
                else if (ViewBag.Status == "Error")
                {
                    <div class="alert alert-danger" id="hideThis">
                        <p> @ViewBag.Message</p>
                    </div>
                }

            </div>
            
        </div>
    </div>
}

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        $(document).ready(function () {

            $("#StudentResultRegNo").change(function () {
                // this will call when Department Dropdown select change
                var studentRegNo = $("#StudentResultRegNo").val();
                if (studentRegNo != null) {


                    var ddStudentName = $('#StudentResultName');
                    ddStudentName.empty();
                    $.ajax({
                        context: this,
                        url: "@Url.Action("GetStudentName", "StudentResults")",
                        type: 'GET',
                        dataType: "json",
                        data: { studentRegNo: studentRegNo },
                        contentType: 'application/json; charset=utf-8',
                        success: function (data) {
                            $('#StudentResultName').text(data);
                        },
                        error: function () {
                            alert("error StudentResultName !");
                        }

                    });


                    var ddStudentEmail = $('#StudentResultEmail');
                    ddStudentName.empty();
                    $.ajax({
                        context: this,
                        url: "@Url.Action("GetStudentEmail", "StudentResults")",
                        type: 'GET',
                        dataType: "json",
                        data: { studentRegNo: studentRegNo },
                        contentType: 'application/json; charset=utf-8',
                        success: function (data) {
                            $('#StudentResultEmail').text(data);
                        },
                        error: function () {
                            alert("error StudentResultEmail !");
                        }

                    });


                    var ddStudentDepartment = $('#StudentResultDepartmentCode');
                    ddStudentDepartment.empty();
                    $.ajax({
                        context: this,
                        url: "@Url.Action("GetStudentDepartment", "StudentResults")",
                        type: 'GET',
                        dataType: "json",
                        data: { studentRegNo: studentRegNo },
                        contentType: 'application/json; charset=utf-8',
                        success: function (data) {
                            $('#StudentResultDepartmentCode').text(data);
                        },
                        error: function () {
                            alert("error StudentResultDepartmentCode !");
                        }

                    });

                }
            });


        });

    </script>



    <script>

        $(document).ready(function () {


            $("#StudentResultRegNo").change(function () {
                // this will call when Department Dropdown select change
                var departmentName = $("#StudentResultRegNo").val();
                if (departmentName != null) {

                    var ddCourseCode = $("#StudentResultCourse");
                    ddCourseCode.empty(); // this line is for clear all items from CourseCode dropdown
                    ddCourseCode.append($("<option></option").val("").html("Select Course"));

                    // Here I will call Controller Action via Jquery to load CourseCode for selected Department
                    $.ajax({
                        url: "@Url.Action("GetCourseCode", "StudentResults")",
                        type: "GET",
                        data: { departmentName: departmentName },
                        dataType: "json",
                        success: function (data) {
                            $.each(data, function (i, val) {
                                ddCourseCode.append(
                                    $("<option></option>").val(val.CourseStudentCourse).html(val.CourseStudentCourse)
                                );
                            });
                        },
                        error: function () {
                            alert("Error GetCourseCode!");
                        }
                    });


                }
            });

        });

    </script>

    <script>
        $(document).ready(function () {
            $(".hideOnClick").click(function () {
                $("#hideThis").hide();
            });
        });
    </script>
}