SaveEmployee/SaveEmployee/Models/ViewResult.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SaveEmployee.Models
{
    public class ViewResult
    {
        [Key]
        [Required(ErrorMessage = "Registration No. is Required!")]
        [DisplayName("Student Reg.No.")]
        public string RegNo { get; set; }


        public string Name { get; set; }

        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        public string Department { get; set; }

        //Result Generating
        [DisplayName("Course Code")]
        public string CourseCode { get; set; }
        [DisplayName("Name")]
        public string CourseName { get; set; }
        [DisplayName("Grade")]
        public string Grade { get; set; }
    }
}

SaveEmployee/SaveEmployee/Controllers/ViewResultController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using SaveEmployee.BLL;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using UniversityApplication.Context;
using UniversityApplication.Models;


namespace SaveEmployee.Controllers
{
    public class ViewResultController : Controller
    {
        private ApplicationContext db = new ApplicationContext();

        // GET: /ViewResult/
        public ActionResult Index()
        {

            return View(db.ViewResults.ToList());
        }

        // GET: /ViewResult/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SaveEmployee.Models.ViewResult viewresult = db.ViewResults.Find(id);
            if (viewresult == null)
            {
                return HttpNotFound();
            }
            return View(viewresult);
        }

        // GET: /ViewResult/Create
        public ActionResult Create()
        {
            List<Student> StudentList = new List<Student>();

            using (ApplicationContext db = new ApplicationContext())
            {
                StudentList = db.Students.OrderBy(m => m.StudentRegNo).ToList();
            }
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (var regNo in StudentList)
            {
                items.Add(new SelectListItem() { Value = regNo.StudentRegNo, Text = regNo.StudentRegNo });
            }

            ViewBag.RegNo = items;

            return View();
        }










        // GET: /ViewResult/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SaveEmployee.Models.ViewResult viewresult = db.ViewResults.Find(id);
            if (viewresult == null)
            {
                return HttpNotFound();
            }
            return View(viewresult);
        }

        // POST: /ViewResult/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RegNo,Name,Email,Department")] SaveEmployee.Models.ViewResult viewresult)
        {
            if (ModelState.IsValid)
            {
                db.Entry(viewresult).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(viewresult);
        }

        // GET: /ViewResult/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SaveEmployee.Models.ViewResult viewresult = db.ViewResults.Find(id);
            if (viewresult == null)
            {
                return HttpNotFound();
            }
            return View(viewresult);
        }

        // POST: /ViewResult/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            SaveEmployee.Models.ViewResult viewresult = db.ViewResults.Find(id);
            db.ViewResults.Remove(viewresult);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }




        public string Name;
        public string Email;
        public string Dept;
        public string RegNo;
        
        //Name
        [HttpGet]
        public JsonResult GetName(string regNo)
        {
            var names = "";
            if (regNo != null)
            {
                using (ApplicationContext db = new ApplicationContext())
                {
                    names = (db.Students.Where(m => m.StudentRegNo == regNo).Select(m => m.StudentName)).Single();
                    Name = names;
                    RegNo = regNo;
                }
            }
            if (Request.IsAjaxRequest())
            {
                return new JsonResult
                {
                    Data = names,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            else
            {
                return new JsonResult
                {
                    Data = "Not valid request",
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
        }


        //Email
        [HttpGet]
        public JsonResult GetEmail(string regNo)
        {
            var emails = "";
            if (regNo != null)
            {
                using (ApplicationContext db = new ApplicationContext())
                {
                    emails = (db.Students.Where(m => m.StudentRegNo == regNo).Select(m => m.StudentEmail)).Single();
                    Email = emails;
                }
            }
            if (Request.IsAjaxRequest())
            {
                return new JsonResult
                {
                    Data = emails,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            else
            {
                return new JsonResult
                {
                    Data = "Not valid request",
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
        }


        //Department
        [HttpGet]
        public JsonResult GetDepartment(string regNo)
        {
            var departments = "";
            if (regNo != null)
            {
                using (ApplicationContext db = new ApplicationContext())
                {
                    departments = (db.Students.Where(m => m.StudentRegNo == regNo).Select(m => m.StudentDepartmentCode)).Single();
                    Dept = departments;
                }
            }
            if (Request.IsAjaxRequest())
            {
                return new JsonResult
                {
                    Data = departments,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            else
            {
                return new JsonResult
                {
                    Data = "Not valid request",
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
        }


        //CourseInfo
        [HttpGet]
        public JsonResult GetCourseInfo(string regNo)
        {
            var resultList = new List<SaveEmployee.Models.ViewResult>();
            if (regNo != null)
            {
                ResultViewManager manager = new ResultViewManager();
                resultList = manager.GetCourseInfos(regNo);
            }
            if (Request.IsAjaxRequest())
            {
                return new JsonResult
                {
                    Data = resultList,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            else
            {
                return new JsonResult
                {
                    Data = "Not valid request",
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
        }




        public void pdf()
        {

            Document pdfDocument = new Document(PageSize.A4, 10f, 10f, 10f, 10f);
            PdfWriter.GetInstance(pdfDocument, Response.OutputStream);

           

            pdfDocument.Open();
            pdfDocument.AddHeader("Header", "Account List");
            //pdfDocument.Add(nameList);
           // pdfDocument.Add(pdfTable);
            pdfDocument.Close();

            Response.ContentType = "application/pdf";
            Response.AppendHeader("content-disposition", "attachment;filename=Official Account List.pdf");
            Response.Write(pdfDocument);
            Response.Flush();
            Response.End();


        }

    }
}

SaveEmployee/SaveEmployee/Views/ViewResult/Create.cshtml
@model SaveEmployee.Models.ViewResult
@*@model IEnumerable<SaveEmployee.Models.ViewResult>*@

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="sidebar">
        <ul>
            <li><a href="../Departments/Create">Save Department</a></li>
            <li><a href="../Departments/ShowAllDepartments">View Departments</a></li>
            <li><a href="../Courses/Create">Save Course</a></li>
            <li><a href="../Teachers/Create">Save Teacher</a></li>
            <li><a href="../CourseTeacher/AssignCourse">Course Assign to Teacher</a></li>
            <li><a href="../CourseStaticss/CourseStatistics">View Course Statics</a></li>
            <li><a href="../Students/Create">Register Student</a></li>
            <li><a href="../Classrooms/AllocateClassRoom">Allocate Classrooms</a></li>
            <li><a href="../Classrooms/ClassScheduleAndRoomAllocation">Class Schedule and Room Allocation</a></li>
            <li><a href="../CourseStudents/StudentToCourse">Enroll in a Course</a></li>
            <li><a href="../StudentResults/SaveResult">Save Student Result</a></li>
            <li class="corners"><a href="../ViewResult/Create">View Result</a></li>
            <li><a href="../Unassign/UnassignCourse">Unassign All Courses</a></li>
            <li><a href="../Unassign/Unallocate">Unallocate All Classrooms</a></li>
        </ul>
    </div>

    <div style="background-color: white; padding-left: 25%; width: 80%; height: 100%;">
        <div class="container body-content">
            <br />
            <div class="form-horizontal">
                <h4>View Result</h4>
                <hr />
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.RegNo, new { @class = "col-md-2 labelStyle" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.RegNo, new SelectList(ViewBag.RegNo, "Value", "Text"), "Select Student Reg.No.", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.RegNo)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "col-md-2 labelStyle" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Name, htmlAttributes: new { @class = "form-control", @style = "text-align:center;font-weight: bold; ", @id = "Name", disabled = "true" })
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, new { @class = "col-md-2 labelStyle" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Email, htmlAttributes: new { @class = "form-control", @style = "text-align:center;font-weight: bold; ", disabled = "true" })
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Department, new { @class = "col-md-2 labelStyle" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Department, htmlAttributes: new { @class = "form-control", @style = "text-align:center;font-weight: bold; ", @id = "Department", disabled = "true" })
                        @Html.ValidationMessageFor(model => model.Department)
                    </div>
                </div>



                <div class="form-group">
                    <div class=" col-sm-5">
                    </div>
                    <div class="col-sm-5">
                        <input type="submit" value="Make PDF" class="btn btn-default" style="width:100px; height:30px" />
                    </div>
                </div>







                <table class="table" id="courseInfo" style="border:1px solid gray">
                    <tr style="background:#f3f3f3">
                        <th style="text-align:center">
                            @Html.DisplayNameFor(model => model.CourseCode)
                        </th>
                        <th style="text-align:center">
                            @Html.DisplayNameFor(model => model.CourseName)
                        </th>
                        <th style="text-align:center">
                            @Html.DisplayNameFor(model => model.Grade)
                        </th>
                    </tr>
                    <tr>
                        <td style="border: 1px solid #cccccc; text-align: center;">
                            <p id="CourseCode"></p>
                        </td>
                        <td style="border: 1px solid #cccccc; text-align: center;">
                            <p id="CourseName"></p>
                        </td>
                        <td style="border: 1px solid #cccccc; text-align: center;">
                            <p id="Grade"></p>
                        </td>
                    </tr>


                </table>
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

@*name*@
<script language="javascript">
    $(document).ready(function () {

        $("#RegNo").change(function () {
            var regNo = $("#RegNo").val();
            if (regNo != null) {
                var name = $("#Name");
                name.empty();

                $.ajax({
                    context: this,
                    url: "@Url.Action("GetName", "ViewResult")",
                    type: "GET",
                    dataType: "json",
                    data: { regNo: regNo },
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        $("#Name").val(data);
                    },
                    error: function () {
                        alert("Error int GetTeachers!");
                    }
                });
            }
        });
    });

</script>


@*email*@
<script language="javascript">
    $(document).ready(function () {

        $("#RegNo").change(function () {
            var regNo = $("#RegNo").val();
            if (regNo != null) {
                var name = $("#Email");
                name.empty();

                $.ajax({
                    context: this,
                    url: "@Url.Action("GetEmail", "ViewResult")",
                    type: "GET",
                    dataType: "json",
                    data: { regNo: regNo },
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        $("#Email").val(data);
                    },
                    error: function () {
                        alert("Error int GetTeachers!");
                    }
                });
            }
        });
    });

</script>


@*department*@
<script language="javascript">
    $(document).ready(function () {

        $("#RegNo").change(function () {
            var regNo = $("#RegNo").val();
            if (regNo != null) {
                var name = $("#Department");
                name.empty();

                $.ajax({
                    context: this,
                    url: "@Url.Action("GetDepartment", "ViewResult")",
                    type: "GET",
                    dataType: "json",
                    data: { regNo: regNo },
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        $("#Department").val(data);
                    },
                    error: function () {
                        alert("Error int GetTeachers!");
                    }
                });
            }
        });
    });

</script>


@* course Information *@
<script language="javascript">
    $(document).ready(function () {

        $("#RegNo").change(function () {
            var regNo = $("#RegNo").val();
            if (regNo != null) {
                var code = $("#CourseCode");
                var name = $("#CourseName");
                var grade = $("#Grade");
                code.empty();
                name.empty();
                grade.empty();

                $.ajax({
                    context: this,
                    url: "@Url.Action("GetCourseInfo", "ViewResult")",
                    type: "GET",
                    dataType: "json",
                    data: { regNo: regNo },
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        $.each(data, function (i, val) {
                            code.append(
                                 $("<option></option>").text(val.CourseCode)
                            );
                            name.append(
                                 $("<option></option>").text(val.CourseName)
                            );
                            grade.append(
                                $("<option></option>").text(val.Grade)
                            );
                        });

                    },
                    error: function () {
                        alert("Error in Get Course Information!");
                    }
                });
            }
        });
    });

</script>

@* PDF writer *@
@*<script language="javascript">
        $(document).ready(function () {

            $("#RegNo").change(function () {
                var regNo = $("#RegNo").val();
                if (regNo != null) {
                    var crsInfo = $("#courseInfo");
                    crsInfo.empty();


                    //var code = $("#CourseCode");
                    //var name = $("#CourseName");
                    //var grade = $("#Grade");
                    //code.empty();
                    //name.empty();
                    //grade.empty();

                    $.ajax({
                        context: this,
                        url: "@Url.Action("GetPDF", "ViewResult")",
                        type: "POST",
                        dataType: "json",
                        data: { regNo: regNo },
                        contentType: 'application/json; charset=utf-8',
                        success: function (data) {
                            $.each(data, function (i, val) {
                                crsInfo.append(
                                     $("<option></option>").text(val.CourseCode)
                                );
                                name.append(
                                     $("<option></option>").text(val.CourseName)
                                );
                                grade.append(
                                    $("<option></option>").text(val.Grade)
                                );
                            });

                        },
                        error: function () {
                            alert("Error in Get Course Information!");
                        }
                    });
                }
            });
        });

    </script>*@

SaveEmployee/SaveEmployee/Views/ViewResult/Delete.cshtml
@model SaveEmployee.Models.ViewResult

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ViewResult</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SaveEmployee/SaveEmployee/Views/ViewResult/Details.cshtml
@model SaveEmployee.Models.ViewResult

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ViewResult</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RegNo }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SaveEmployee/SaveEmployee/Views/ViewResult/Edit.cshtml
@model SaveEmployee.Models.ViewResult

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ViewResult</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.RegNo)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department)
                @Html.ValidationMessageFor(model => model.Department)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SaveEmployee/SaveEmployee/Views/ViewResult/Index.cshtml
@model IEnumerable<SaveEmployee.Models.ViewResult>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Department)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.RegNo }) |
            @Html.ActionLink("Details", "Details", new { id=item.RegNo }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.RegNo })
        </td>
    </tr>
}

</table>